src/Entity/Jardinier.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use App\Entity\Vegetal;

/**
 * @ORM\Entity(repositoryClass="App\Repository\JardinierRepository")
 */
class Jardinier extends User
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $outil;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $mission;

    /**
     * @ORM\ManyToMany(targetEntity="Vegetal", inversedBy="jardiniers", cascade={"persist"})
     */
    private $vegetals;

    public function __construct()
    {
        $this->vegetals = new ArrayCollection();
    }

    // public function getId(): ?int
    // {
    //     return $this->id;
    // }

    public function getOutil(): ?string
    {
        return $this->outil;
    }

    public function setOutil(string $outil): self
    {
        $this->outil = $outil;

        return $this;
    }

    public function getMission(): ?string
    {
        return $this->mission;
    }

    public function setMission(string $mission): self
    {
        $this->mission = $mission;

        return $this;
    }

    /**
     * @return Collection|Vegetal[]
     */
    public function getVegetals(): Collection
    {
        return $this->vegetals;
    }

    public function addVegetal(Vegetal $vegetal): self
    {
        if ($this->vegetals->contains($vegetal)) {
            return $this;
        }
        
        $this->vegetals[] = $vegetal;
        $vegetal->addJardinier($this);
        return $this;
    }

    public function removeVegetal(Vegetal $vegetal): self
    {
        if ($this->vegetals->contains($vegetal)) {
            $this->vegetals->removeElement($vegetal);
        }

        return $this;
    }

    public function __toString()
    {
        return $this->nom;
    }

    public function getClassName()
    {
        return (new \ReflectionClass($this))->getShortName();
    }

}

src/Entity/User.php
<?php
namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity
 * @ORM\InheritanceType("SINGLE_TABLE")
 * @ORM\DiscriminatorColumn(name="discr", type="string")
 * @ORM\DiscriminatorMap({
 * 	"user" = "User",
 *  "jardinier" = "Jardinier",
 *  "mangeur" = "Mangeur"
 * 	})
 */
class User
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Oups tu as ounlié le nom!")
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Oups tu as ounlié le prenom!")
     */
    private $prenom;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getFullName(): ?string
    {
        return $this->prenom . " " . $this->nom;
    }

}

src/Controller/JardinierController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\JardinierRepository;

/**
 * @Route("/{_locale}/jardinier", name="jardinier_")
 */
class JardinierController extends AbstractController
{
    /**
 	 * @Route("/", name="index")
 	 */
    public function indexAction(JardinierRepository $jardinierRepo)
    {
    	$jardiniers = $jardinierRepo->giveMeAllJardinier();
    	$jardiniersFleur = $jardinierRepo->giveMeAllJardinierFleur('fleur');
    	$jardiniersArbre = $jardinierRepo->giveMeAllJardinierArbre('arbre');

        return $this->render('jardinier/index.html.twig', [
            'jardiniers' => $jardiniers,
            'jardiniersFleur' => $jardiniersFleur,
            'jardiniersArbre' => $jardiniersArbre

        ]);
    }

    
}

templates/jardinier/index.html.twig
{% extends 'base.html.twig' %}

{% block title %} Au jardin {% endblock %}

{% block body %}
	<div class="jumbotron">
		<div class="container">
			<h1 class="display-3">
				{{ 'pageTitle'|trans({},'jardinierIndex')|title }}
			</h1>
		</div>
	</div>

	<div class="container">
		<h2>{{ 'pageTitle'|trans({},'jardinierIndex')|title }}</h2>
	    <div class="row">
	     {% for jardinier in jardiniers %}
			<div class="col-md-4">
				<h3>{{ jardinier.fullName }}</h3>
				<p>{{ jardinier.description }}</p>
				<p>
					<ul>
						<li>Outil: {{ jardinier.outil }}</li>
						<li>Mission: {{ jardinier.mission }}</li>
					</ul>
				</p>
				<p>
					Vegétaux cultivés:
					<ul>
						{% for vegetal in jardinier.vegetals %}
							<li> {{ vegetal.nom }} ( {{ vegetal.className }} )</li>
						{% endfor %}
					</ul>
				</p>
			</div>
			{% endfor %}
		</div>
	</div>

    <hr>

    <div class="container">
		<div class="row">
			<div class="col-md-4">
				<h3>{{ 'pageTitle'|trans({},'jardinierIndex')|title }}</h3>
				{% for jardinier in jardiniers %}
					<h4>{{ jardinier.fullName }}</h4>
				{% endfor %}
	      	</div>
			<div class="col-md-4">
				<h3>{{ 'title1'|trans({},'jardinierIndex')|title }}</h3>
				{% for jardiFleur in jardiniersFleur %}
					<h4>{{ jardiFleur.fullName }}</h4>
				{% endfor %}
			</div>
	      	<div class="col-md-4">
				<h3>{{ 'title2'|trans({},'jardinierIndex')|title }}</h3>
				{% for jardiArbre in jardiniersArbre %}
					<h4>{{ jardiArbre.fullName }}</h4>
				{% endfor %}
			</div>
		</div>
	</div>    

    <hr>

{% endblock %}