src/Entity/Fleur.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use App\Entity\Mangeur;
use App\Entity\Vegetal;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\FleurRepository")
 */
class Fleur extends Vegetal 
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Gedmo\Translatable
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $bouquet;

    /**
     * @Gedmo\Translatable
     * @ORM\Column(type="string", length=255)
     */
    private $couleur;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Legume", mappedBy="fleurs")
     */
    private $legumes;

    public function __construct()
    {
        parent::__construct();
        $this->legumes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return parent::getId();
    }

    public function getBouquet(): ?string
    {
        return $this->bouquet;
    }

    public function setBouquet(?string $bouquet): self
    {
        $this->bouquet = $bouquet;

        return $this;
    }

    public function getCouleur(): ?string
    {
        return $this->couleur;
    }

    public function setCouleur(string $couleur): self
    {
        $this->couleur = $couleur;

        return $this;
    }

    // https://stackoverflow.com/questions/22550368/how-can-we-get-class-name-of-the-entity-object-in-twig-view
    public function getClassName()
    {
        return (new \ReflectionClass($this))->getShortName();
    }

    /**
     * @return Collection|Jardinier[]
     */
    public function getJardiniers(): Collection
    {
        return parent::getJardiniers();
    }

    /**
     * @return Collection|Legume[]
     */
    public function getLegumes(): Collection
    {
        return $this->legumes;
    }

    public function addLegume(Legume $legume): self
    {
        if ($this->legumes->contains($legume)) {
           return $this; 
        }
        $this->legumes[] = $legume;
        $legume->addFleur($this);
        return $this;
    }

    public function removeLegume(Legume $legume): self
    {
        if (!$this->legumes->contains($legume)) {
           return $this; 
        }
        $this->legumes->removeElement($legume);
        $legume->removeFleur($this);
        return $this;
    }
}

src/Entity/Fruit.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use App\Entity\Mangeur;
use App\Entity\Arbre;

/**
 * @ORM\Entity(repositoryClass="App\Repository\FruitRepository")
 */
class Fruit extends Vegetal
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $salade;

    /**
     * @ORM\ManyToOne(targetEntity="Arbre", inversedBy="fruits")
     * @ORM\JoinColumn(nullable=false)
     */
    private $arbre;

    public function __construct()
    {
        parent::__construct();
        $this->arbres = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return parent::getId();
    }

    public function getSalade(): ?string
    {
        return $this->salade;
    }

    public function setSalade(?string $salade): self
    {
        $this->salade = $salade;

        return $this;
    }

    public function getClassName()
    {
        return (new \ReflectionClass($this))->getShortName();
    }

    public function getArbre(): ?Arbre
    {
        return $this->arbre;
    }

    public function setArbre(?Arbre $arbre): self
    {
        $this->arbre = $arbre;

        return $this;
    }

}

src/Entity/User.php
<?php
namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity
 * @ORM\InheritanceType("SINGLE_TABLE")
 * @ORM\DiscriminatorColumn(name="discr", type="string")
 * @ORM\DiscriminatorMap({
 * 	"user" = "User",
 *  "jardinier" = "Jardinier",
 *  "mangeur" = "Mangeur"
 * 	})
 */
class User
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Oups tu as ounlié le nom!")
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Oups tu as ounlié le prenom!")
     */
    private $prenom;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getFullName(): ?string
    {
        return $this->prenom . " " . $this->nom;
    }

}

src/Controller/FruitController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\FruitRepository;
use App\Repository\ArbreRepository;

/**
 * @Route("/fruit", name="fruit_")
 */
class FruitController extends AbstractController
{
    /**
     * @Route("/", name="index")
     */
    public function indexAction(FruitRepository $fruitrepo)
    {
    	// $fruits = $fruitrepo->findAll();
        $fruits = $fruitrepo->giveMeAllFruit();

        $arbres = $fruitrepo->giveMeAllArbresDQL();

        $arbresAfruits = $fruitrepo->giveMeAllArbresWithFruitsDQL();

        return $this->render('fruit/index.html.twig', [
        	'fruits' => $fruits,
            'arbres' => $arbres,
            'arbresAfruits' => $arbresAfruits
        ]);
    }
}

templates/fruit/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Les fruits{% endblock %}

{% block body %}
	<div class="jumbotron">
		<div class="container">
			<h1 class="display-3">Les fruits et les arbres !</h1>
		</div>
	</div>

	<div class="container">
		<div class="row">
			<div class="col-sm-12">
				<h2>Les fruits</h2>
			</div>
			{% for fruit in fruits %}
			<div class="col-md-4">
				<h3>{{ fruit.nom }}</h3>
				<br>
				<p>{{ fruit.description }}</p>
				<p>
					<ul>
						<li>Arbre: {{ fruit.arbre.nom }}</li>
						<li>Salade de {{ fruit.salade }}</li>
					</ul>
				</p>
				<p>
					Mangeur: {{ fruit.mangeur.fullName }}
				</p>
				<p> Jardinniers: 
					{% for jardinier in fruit.jardiniers %}
						{{ jardinier.fullName }}
					{% else %}
						M.Nobody
					{% endfor %}
				</p>
			</div>
			{% endfor %}
		</div>
	</div>
	<hr>
	<div class="container">
		<div class="row">
			<div class="col-sm-12">
				<h2>Les arbres</h2>
			</div>
			<br>
			{% for arbre in arbres %}
			<div class="col-md-4">
				<h3>{{ arbre.nom }}</h3>
				<p>{{ arbre.description }}</p>
				<p> Cultivé par
					{% for jardinier in arbre.jardiniers %}
						{{ jardinier.fullName }}
					{% else %}
						Mr.Nobody
					{% endfor %}	
				</p>
				<p>Fruits:
					{% for fruit in arbre.fruits %}
						{{ fruit.nom }} 
					{% else %}
						NO FRUIT 
					{% endfor %}
				</p>
			</div>
			{% endfor %}
		</div>
	</div>
	<hr>
	<div class="container">
		<div class="row">
			<div class="col-sm-12">
				<h2>Les arbres à fruits</h2>
			</div>
			<br>
			{% for arbre in arbresAfruits %}
			<div class="col-md-4">
				<h3>{{ arbre.nom }}</h3>
				<p>{{ arbre.description }}</p>
				<p> Cultivé par
					{% for jardinier in arbre.jardiniers %}
						{{ jardinier.fullName }}
					{% else %}
						Mr.Nobody
					{% endfor %}	
				</p>
				<p>Fruits:
					{% for fruit in arbre.fruits %}
						{{ fruit.nom }} 
					{% else %}
						NO FRUIT 
					{% endfor %}
				</p>
			</div>
			{% endfor %}
		</div>
	</div>
{% endblock %}